### ISSUE TITLE
Redis session problem 

### ISSUE THREAD

**Issue by ubcent** [opis/session#5]
Hello. We are using your session lib with Redis and it has some bug. We fixed this:

lib/Storage/Redis.php:124
```php
-return (bool) $this->redis->delete($this->prefix . $id); 
```
Redis client hasn't method "delete"
```php
+return (bool) $this->redis->del($this->prefix . $id);
```
Sorry for my English. Thanks:-)

**Comment by msarca** [comment]
Fixed. Thanks for reporting. https://github.com/opis/session/commit/cb46f2db3fe5203af56a8f383679b90fb6e11633
