### ISSUE TITLE
Move optional dependencies to require-dev and suggests

### ISSUE THREAD

**Issue by nebulousGirl** [opis/session#6]
I quite like the simplicity of your session package and the fact that you use PHP's SessionHandlerInterface, I was looking for something like this.

But, I don't like to load packages that have dependencies that I don't plan on using. I suggest to move opis/database, predis/predis in require-dev. And use suggests to mention that they are needed for certain handlers

Like so:
```
"require": {
        "php": ">=5.3.0"
 },
"require-dev": {
        "opis/database": "^2.1.1",
        "predis/predis": "1.0.*"
 },
"suggests": {
         "opis/database": "Needed to use database to store sessions",
         "predis/predis": "Needed to use redis to store sessions"
}
```

**Comment by msarca** [comment]
You are right. This is something that needs to be changed. In fact, when this project was created, [my approach](https://github.com/opis/session/blob/3c493a3eacad2c4eae35eb0de79883db7bc1ce1f/composer.json#L16) was similar to your proposal. Dependencies were added later to make sure that nobody will try to use this library with an unsupported version of Predis or Opis Database.

I'll issue a new major version in the following hours and I will move into a separate package all adapters that have dependencies, just so I can keep version constraints regarding Predis and Opis Database libraries.

**Comment by msarca** [comment]
Dependencies were removed and a new version was released
